version: '3.8'
services:
  db-mysql:
    container_name: db-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: COMMON
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - ./mysql/InitDatabase.sql:/docker-entrypoint-initdb.d/1.sql:ro
    security_opt:
      - seccomp:unconfined

  db-redis:
    container_name: db-redis
    image: redis:6.2
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - default